// <auto-generated />
using System;
using FriendOrganizer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FriendOrganizer.DataAccess.Migrations
{
    [DbContext(typeof(FriendOrganizerContext))]
    [Migration("20210421122503_AddedProgrammingLanguage")]
    partial class AddedProgrammingLanguage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FriendOrganizer.Model.Friend", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FavoriteLanguageID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("FavoriteLanguageID");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Bobe",
                            LastName = "Turboto"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Stefko",
                            LastName = "Oboista"
                        },
                        new
                        {
                            ID = 3,
                            FirstName = "Mario",
                            LastName = "Kitarista"
                        },
                        new
                        {
                            ID = 4,
                            FirstName = "Forever",
                            LastName = "Alone"
                        });
                });

            modelBuilder.Entity("FriendOrganizer.Model.ProgrammingLanguage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "C#"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Java"
                        },
                        new
                        {
                            ID = 3,
                            Name = "JavaScript"
                        },
                        new
                        {
                            ID = 4,
                            Name = "PHP"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Python"
                        });
                });

            modelBuilder.Entity("FriendOrganizer.Model.Friend", b =>
                {
                    b.HasOne("FriendOrganizer.Model.ProgrammingLanguage", "FavoriteLanguage")
                        .WithMany()
                        .HasForeignKey("FavoriteLanguageID");

                    b.Navigation("FavoriteLanguage");
                });
#pragma warning restore 612, 618
        }
    }
}
